title: Surajgaud.GitHub.io
description: A page about me, my works and interests.
google_analytics: 
show_downloads: true
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gems:
  - jekyll-mentions
